### PR TITLE
Use PostgreSQL instead of sqlite

### LINKED ISSUE #129: Don't store job data in /tmp
The default place to store the jobs is:

    SQLALCHEMY_DATABASE_URI = 'sqlite:////tmp/job_store.db'

and tmp is wiped on reboot (or even [daily](http://askubuntu.com/questions/20783/how-is-the-tmp-directory-cleaned-up/759048#759048))

This is no good, because it results in problems like this:
https://github.com/ckan/ckan/issues/3156

We should store it somewhere better by default.

### PR DESCRIPTION
**Pull request by jqnatividad**
Implements #198 and fixes #129.

### CODE REVIEW

**Comment by mbocevski** [comment]
@jqnatividad I think that for most users of datapusher, sqlite is good enough and should be default. Considering SQLAlchemy is used, different backend are supported. So I would suggest to just update the documentation about using Postgres as a backend for datapusher and not change the default sqlite configuration.

**Comment by jqnatividad** [comment]
@mbocevski thanks for your feedback.  However, sqlite won't work for a truly asynchronous, concurrent datapusher because you will get a "sqlite Operational Error: Database is Locked error" as it cannot support more than one thread writing to the database.

https://stackoverflow.com/questions/3172929/operationalerror-database-is-locked/3172950

You can make it work by increasing the timeout, but then doing so effectively makes datapusher single-threaded again, even if you configure uwsgi to make it concurrent (https://github.com/ckan/datapusher/pull/201).

**Comment by mbocevski** [comment]
Yes that is clear, however I'm suggesting that a lot of users might not need datapusher to be concurrent and I'm suggesting to document how to make datapusher concurrent and provide configuration for those that need it to be concurrent. WDYT?

**Comment by jqnatividad** [comment]
@mbocevski I'll amend the PR so that the user can be given both options and document the implications of each. Thanks!

**Comment by mbocevski** [comment]
@jqnatividad Yeah I agree with that. Considering lots of folks would be deploying datapusher on the same box as CKAN. maybe we should store it by default in `/var/lib/ckan`?

**Comment by amercader** [comment]
@jqnatividad @mbocevski please check #207, particularly the new section that describes this setup

**Pull request closed without merging**
